# Copyright 2025 The Torch-Spyre Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""End-to-end validation of the sliding-window tiling prototype (increments 1-3).

Unlike the probes, this runs a sliding read produced ENTIRELY by the frontend
(the new spyre_hint(sliding=...) path) — no hand-mutated bundle. It is the real
test that increments 1-3 wire together correctly:

    spyre_hint(sliding=...)  -> DimHint(read_extent, slide_stride)         [inc 1]
    -> _divide_reduction_ranges(window=...) + CoarseTileInfo               [inc 2]
    -> OpSpec.sliding_symbols                                              [inc 3b/c]
    -> generate_sdsc affine-stride scaling  (stride * slide // extent)     [inc 3d]
    -> scf.for whose input base advances by slide_stride, reads read_extent

The op is a PLAIN reduction `x.sum(dim=0)` with a sliding hint on the reduction
dim.  With window W > stride S the loop reads overlapping windows and
accumulates them, so the result is the coverage-weighted sum
`sum_i x[i*S : i*S+W].sum(0)` — the same reference probe_windowed_numeric.py
validated, but now the overlap is generated by the compiler, not injected by
mutating MLIR.  A reduction (not a pointwise op) is required so the input read
stride and the output accumulator stride genuinely differ.

SENCORES=1 keeps it single-core (no work-division to debug simultaneously).
D, W, S are chosen so (D - W) % S == 0 (windows tile the dim) and W | D (clean
single-core layout): D=256, W=128, S=64 -> 3 windows overlapping by 64.

Run:
    python3 validate_sliding_prototype.py
"""

import os

os.environ.setdefault("SENCORES", "1")

import regex as re  # noqa: E402
import torch  # noqa: E402
import torch_spyre  # noqa: E402, F401
from torch._inductor.runtime.runtime_utils import cache_dir  # noqa: E402

DEVICE = torch.device("spyre")
BUNDLE_ROOT = os.path.join(cache_dir(), "inductor-spyre")

ROWS = 256  # dim "A" — the reduction dim, slid over
# COLS = 64 => a SINGLE 64-element stick (isolate the sliding mechanism from the
# multi-stick addressing bug: with COLS=128 = 2 sticks, stick0 is numerically
# correct but stick1 is wrong — the slide isn't propagating to the 2nd col-stick).
# Set back to 128 to reproduce the multi-stick failure.
COLS = 128  # dim "B" — 2 col-sticks (multi-stick addressing investigation)
WINDOW = 128  # W
STRIDE = 64  # S  (< W => overlap of 64)

_AFFINE_MAP = re.compile(r"#map_\d+ = affine_map")


def _snapshot() -> set[str]:
    return set(os.listdir(BUNDLE_ROOT)) if os.path.isdir(BUNDLE_ROOT) else set()


def _cpu_overlap_reference(x: torch.Tensor) -> torch.Tensor:
    """The coverage-weighted sum the sliding reduction should produce.

    PARTITION+SLIDE model: loop_count = num_tiles = ROWS // WINDOW (so
    count * read == ROWS, the clean partition the reduction machinery wants).
    The overlap comes from slide (STRIDE) < read (WINDOW).  With W=128, S=64,
    ROWS=256 this is 2 windows: x[0:128] + x[64:192] (covers rows 0-191).
    """
    num_tiles = ROWS // WINDOW
    acc = torch.zeros(COLS, dtype=torch.float32)
    for i in range(num_tiles):
        lo = STRIDE * i
        acc += x[lo : lo + WINDOW].to(torch.float32).sum(dim=0)
    return acc


def _dump_affine_maps(new_dirs: set[str]) -> None:
    """Dump the full bundle.mlir of any loop-bearing bundle (loop bound, affine
    maps, sdsc_execute structure) so the read width / trip count are visible."""
    for name in sorted(new_dirs):
        mlir = os.path.join(BUNDLE_ROOT, name, "bundle.mlir")
        if not os.path.isfile(mlir):
            continue
        with open(mlir) as f:
            text = f.read()
        if "scf.for" not in text:
            continue
        print(f"    --- {os.path.basename(name)}/bundle.mlir ---")
        for ln in text.splitlines():
            print(f"      {ln}")
        # Extract just the geometry fields from each sdsc JSON (compact, so it
        # doesn't scroll off).  sdsc_1 is the sliding x-read — its size/dims are
        # the ground truth for how many rows are read per iteration.
        import json

        geom_re = re.compile(
            r"size|dim|iter|range|stride|extent|scale|count|length|shape|span|host|dev",
            re.I,
        )

        def _geom(d, path=""):
            out = []
            if isinstance(d, dict):
                for k, v in d.items():
                    # A short list of ints is almost always a size/shape/stride.
                    if isinstance(v, list) and v and all(isinstance(e, int) for e in v):
                        out.append((f"{path}.{k}", v))
                    elif isinstance(v, (dict, list)):
                        out += _geom(v, f"{path}.{k}")
                    elif geom_re.search(str(k)):
                        out.append((f"{path}.{k}", v))
            elif isinstance(d, list):
                for idx, v in enumerate(d):
                    out += _geom(v, f"{path}[{idx}]")
            return out

        for js in sorted(os.listdir(os.path.join(BUNDLE_ROOT, name))):
            if not js.endswith(".json"):
                continue
            with open(os.path.join(BUNDLE_ROOT, name, js)) as f:
                d = json.load(f)
            print(f"      --- {js} geometry ---")
            for pth, val in _geom(d):
                print(f"        {pth} = {val}")


def main() -> None:
    torch.manual_seed(0xAFFE)
    print(f"SENCORES={os.environ.get('SENCORES')}")
    print(
        f"D={ROWS} W={WINDOW} S={STRIDE} -> "
        f"{ROWS // WINDOW} tiles (partition+slide), overlap {WINDOW - STRIDE}"
    )
    print("=" * 78)

    from torch_spyre._inductor import config, spyre_hint
    import torch_spyre._inductor.propagate_named_dims as _pnd

    _pnd.reset()
    torch._dynamo.reset_code_caches()
    torch._inductor.codecache.FxGraphCache.clear()

    x = torch.randn(ROWS, COLS, dtype=torch.float16)

    def fn(x):
        with spyre_hint(sliding={"A": {"window": WINDOW, "stride": STRIDE}}):
            return x.sum(dim=0)

    x_dev = x.to(DEVICE)
    _pnd.declare_tensor_dim("A", ROWS)
    _pnd.declare_tensor_dim("B", COLS)
    _pnd.name_tensor_dims(x_dev, ["A", "B"])

    before = _snapshot()
    try:
        with config.patch({"lx_planning": True, "allow_all_ops_in_lx_planning": True}):
            got = torch.compile(fn)(x_dev).to("cpu", torch.float32)
    except Exception as e:  # noqa: BLE001 — surface compile/codegen failures
        print(f"COMPILE/RUN FAILED: {type(e).__name__}: {e}")
        print("Bundles emitted before the failure:")
        _dump_affine_maps(_snapshot() - before)
        raise

    print("bundle(s) emitted:")
    _dump_affine_maps(_snapshot() - before)

    ref = _cpu_overlap_reference(x)
    full = x.to(torch.float32).sum(dim=0)  # what a NON-overlapping read gives
    max_err = (got - ref).abs().max().item()
    ok = torch.allclose(got, ref, rtol=2e-2, atol=ref.abs().max().item() * 2e-2)

    # Reverse-engineer what the kernel ACTUALLY computed: try candidate
    # (num_iters, read_width, slide_stride) geometries and report which matches.
    def _candidate(n_iters, width, stride):
        acc = torch.zeros(COLS, dtype=torch.float32)
        for i in range(n_iters):
            lo = stride * i
            hi = min(lo + width, ROWS)
            if lo < ROWS:
                acc += x[lo:hi].to(torch.float32).sum(dim=0)
        return acc

    print("  reverse-engineering the compiled output (n_iters, width, stride):")
    for ni, w, s in [
        (3, 128, 64),
        (2, 128, 64),
        (3, 64, 64),
        (2, 128, 128),
        (3, 128, 128),
        (3, 256, 64),
        (4, 64, 64),
        (2, 128, 32),
        (3, 128, 32),
    ]:
        cand = _candidate(ni, w, s)
        match = torch.allclose(
            got, cand, rtol=2e-2, atol=cand.abs().max().item() * 2e-2 + 1e-3
        )
        print(
            f"    ({ni:>2}, w={w:>3}, s={s:>3}) peak={cand.abs().max().item():>7.3f}"
            f"{'   <== MATCH' if match else ''}"
        )

    # Peak-matches-but-element-wise-mismatch is the signature of a COLUMN-ORDERING
    # (stick-layout) difference between the device output and the natural-order CPU
    # reference: the values can be correct but permuted.  Compare the sorted vectors
    # to tell "right values, reordered" (permutation) from "wrong values".
    sorted_match = torch.allclose(
        got.sort().values,
        ref.sort().values,
        rtol=2e-2,
        atol=ref.abs().max().item() * 2e-2,
    )

    print()
    print(f"  overlap reference peak: {ref.abs().max().item():.3f}")
    print(
        f"  plain full-sum   peak: {full.abs().max().item():.3f} "
        "(what NO overlap would give)"
    )
    print(f"  compiled output   peak: {got.abs().max().item():.3f}")
    print(
        f"  max|got - overlap_ref| = {max_err:.4f} -> {'MATCH' if ok else 'MISMATCH'}"
    )
    print(
        f"  PERMUTATION TEST (sorted got vs sorted overlap_ref): {bool(sorted_match)}"
    )
    # Per-column error localisation.  128 output cols = 2 sticks of 64; if the
    # slide works for stick 0 but not stick 1, cols[0:64] match and cols[64:128]
    # are wrong.  Also show how many cols match and the worst offenders.
    per_col_err = (got - ref).abs()
    tol = ref.abs().max().item() * 2e-2 + 0.2
    n_match = int((per_col_err <= tol).sum())
    half = COLS // 2
    err_stick0 = per_col_err[:half].max().item()
    err_stick1 = per_col_err[half:].max().item()
    worst = per_col_err.argsort(descending=True)[:6].tolist()
    print(f"    columns matching (tol {tol:.2f}): {n_match}/{COLS}")
    print(
        f"    max err  cols[0:{half}] (stick0) = {err_stick0:.3f}   "
        f"cols[{half}:{COLS}] (stick1) = {err_stick1:.3f}"
    )
    print("    worst cols (col: got vs ref):")
    for c in worst:
        print(f"      col {c:>3}: got={got[c].item():>8.2f}  ref={ref[c].item():>8.2f}")
    print()
    if ok:
        print("  RESULT: the frontend-generated sliding read is NUMERICALLY")
        print("  CORRECT. Increments 1-3 compose end-to-end: spyre_hint(sliding=)")
        print("  produces a real overlapping windowed read that computes the")
        print("  coverage-weighted sum. The prototype works at SENCORES=1.")
    elif sorted_match:
        print("  RESULT: CORRECT VALUES, DIFFERENT ORDER. got is a permutation of")
        print("  the overlap reference (same multiset of column sums) — the")
        print("  element-wise mismatch is a stick-layout COLUMN-ORDERING artifact,")
        print("  not a computation error. The sliding reduction is numerically")
        print("  correct; only the output column order differs from natural order.")
    elif torch.allclose(got, full, rtol=2e-2, atol=full.abs().max().item() * 2e-2):
        print("  RESULT: output matches the PLAIN full sum, not the overlap ref.")
        print("  => The stride override did not take effect (read did not slide).")
        print("  Check that sliding_symbols reached generate_sdsc for the input.")
    else:
        print("  RESULT: output matches NEITHER reference (values, not just order,")
        print("  differ). Slide stride is correct now, so the residual is in the")
        print("  reduction accumulation over overlapping tiles — inspect the log.")


if __name__ == "__main__":
    main()
