# Copyright 2025 The Torch-Spyre Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""End-to-end validation of the sliding-window tiling prototype (increments 1-3).

Unlike the probes, this runs a sliding read produced ENTIRELY by the frontend
(the new spyre_hint(sliding=...) path) — no hand-mutated bundle. It is the real
test that increments 1-3 wire together correctly:

    spyre_hint(sliding=...)  -> DimHint(read_extent, slide_stride)         [inc 1]
    -> _divide_reduction_ranges(window=...) + CoarseTileInfo               [inc 2]
    -> OpSpec.sliding_symbols                                              [inc 3b/c]
    -> generate_sdsc affine-stride scaling  (stride * slide // extent)     [inc 3d]
    -> scf.for whose input base advances by slide_stride, reads read_extent

The op is a PLAIN reduction `x.sum(dim=0)` with a sliding hint on the reduction
dim.  With window W > stride S the loop reads overlapping windows and
accumulates them, so the result is the coverage-weighted sum
`sum_i x[i*S : i*S+W].sum(0)` — the same reference probe_windowed_numeric.py
validated, but now the overlap is generated by the compiler, not injected by
mutating MLIR.  A reduction (not a pointwise op) is required so the input read
stride and the output accumulator stride genuinely differ.

SENCORES=1 keeps it single-core (no work-division to debug simultaneously).

Shape constraints (frontend today):
  * WINDOW | ROWS      — split_count = ROWS // WINDOW, so the window must divide
                         the reduction dim evenly.
  * COLS % 64 == 0     — COLS spans whole 64-element sticks (COLS // 64 sticks).
  * STRIDE < WINDOW    — otherwise there is no overlap (plain partition).

Run:
    python3 validate_sliding_prototype.py                    # default single shape
    python3 validate_sliding_prototype.py --rows 512 --cols 192 --window 128 --stride 64
    python3 validate_sliding_prototype.py --sweep            # shape-hardening sweep
"""

import argparse
import os

os.environ.setdefault("SENCORES", "1")

import regex as re  # noqa: E402
import torch  # noqa: E402
import torch_spyre  # noqa: E402, F401
from torch._inductor.runtime.runtime_utils import cache_dir  # noqa: E402

DEVICE = torch.device("spyre")
BUNDLE_ROOT = os.path.join(cache_dir(), "inductor-spyre")
STICK = 64  # elements per stick at fp16

# Defaults (overridable via CLI).  ROWS=256, WINDOW=128, STRIDE=64, COLS=128 is
# the 2-col-stick multi-stick case: 2 windows x[0:128] + x[64:192], overlap 64.
DEFAULT_ROWS = 256
DEFAULT_COLS = 128
DEFAULT_WINDOW = 128
DEFAULT_STRIDE = 64

# Shape-hardening sweep: exercises >2 sticks, more windows, and W!=2*S.  Every
# entry obeys WINDOW | ROWS and COLS % 64 == 0.
SWEEP_SHAPES = [
    # (rows, cols, window, stride)   note
    (256, 64, 128, 64),  # 1 stick, 2 windows  (single-stick baseline)
    (256, 128, 128, 64),  # 2 sticks, 2 windows (the fixed multi-stick case)
    (256, 192, 128, 64),  # 3 sticks
    (256, 256, 128, 64),  # 4 sticks
    (512, 128, 128, 64),  # 2 sticks, 4 windows (more loop iterations)
    (384, 128, 128, 64),  # 3 windows
    (512, 128, 256, 128),  # 2 tiles, larger window W=256 S=128 (overlap 128)
    (512, 192, 256, 64),  # 3 sticks, 2 tiles, W=256 S=64 (overlap 192)
]

_AFFINE_MAP = re.compile(r"#map_\d+ = affine_map")


def _snapshot() -> set[str]:
    return set(os.listdir(BUNDLE_ROOT)) if os.path.isdir(BUNDLE_ROOT) else set()


def _cpu_overlap_reference(
    x: torch.Tensor, rows: int, cols: int, window: int, stride: int
) -> torch.Tensor:
    """The coverage-weighted sum the sliding reduction should produce.

    PARTITION+SLIDE model: loop_count = num_tiles = ROWS // WINDOW (so
    count * read == ROWS, the clean partition the reduction machinery wants).
    The overlap comes from slide (STRIDE) < read (WINDOW).  With W=128, S=64,
    ROWS=256 this is 2 windows: x[0:128] + x[64:192] (covers rows 0-191).
    """
    num_tiles = rows // window
    acc = torch.zeros(cols, dtype=torch.float32)
    for i in range(num_tiles):
        lo = stride * i
        acc += x[lo : lo + window].to(torch.float32).sum(dim=0)
    return acc


def _dump_affine_maps(new_dirs: set[str]) -> None:
    """Dump the full bundle.mlir of any loop-bearing bundle (loop bound, affine
    maps, sdsc_execute structure) so the read width / trip count are visible."""
    for name in sorted(new_dirs):
        mlir = os.path.join(BUNDLE_ROOT, name, "bundle.mlir")
        if not os.path.isfile(mlir):
            continue
        with open(mlir) as f:
            text = f.read()
        if "scf.for" not in text:
            continue
        print(f"    --- {os.path.basename(name)}/bundle.mlir ---")
        for ln in text.splitlines():
            print(f"      {ln}")
        # Extract just the geometry fields from each sdsc JSON (compact, so it
        # doesn't scroll off).  sdsc_1 is the sliding x-read — its size/dims are
        # the ground truth for how many rows are read per iteration.
        import json

        geom_re = re.compile(
            r"size|dim|iter|range|stride|extent|scale|count|length|shape|span|host|dev",
            re.I,
        )

        def _geom(d, path=""):
            out = []
            if isinstance(d, dict):
                for k, v in d.items():
                    # A short list of ints is almost always a size/shape/stride.
                    if isinstance(v, list) and v and all(isinstance(e, int) for e in v):
                        out.append((f"{path}.{k}", v))
                    elif isinstance(v, (dict, list)):
                        out += _geom(v, f"{path}.{k}")
                    elif geom_re.search(str(k)):
                        out.append((f"{path}.{k}", v))
            elif isinstance(d, list):
                for idx, v in enumerate(d):
                    out += _geom(v, f"{path}[{idx}]")
            return out

        for js in sorted(os.listdir(os.path.join(BUNDLE_ROOT, name))):
            if not js.endswith(".json"):
                continue
            with open(os.path.join(BUNDLE_ROOT, name, js)) as f:
                d = json.load(f)
            print(f"      --- {js} geometry ---")
            for pth, val in _geom(d):
                print(f"        {pth} = {val}")


def run_one(rows: int, cols: int, window: int, stride: int, dump: bool = True) -> bool:
    """Compile x.sum(dim=0) with a sliding hint and check numerics on HW.

    Returns True when the compiled output matches the coverage-weighted overlap
    reference.  Prints a per-stick error breakdown so a partial failure (some
    sticks right, some wrong) is immediately visible.
    """
    assert rows % window == 0, f"WINDOW {window} must divide ROWS {rows}"
    assert cols % STICK == 0, f"COLS {cols} must be a multiple of {STICK}"
    n_sticks = cols // STICK
    print("=" * 78)
    print(
        f"SENCORES={os.environ.get('SENCORES')}  "
        f"D={rows} COLS={cols} ({n_sticks} stick(s)) W={window} S={stride} -> "
        f"{rows // window} tiles (partition+slide), overlap {window - stride}"
    )

    torch.manual_seed(0xAFFE)
    from torch_spyre._inductor import config, spyre_hint
    import torch_spyre._inductor.propagate_named_dims as _pnd

    _pnd.reset()
    torch._dynamo.reset_code_caches()
    torch._inductor.codecache.FxGraphCache.clear()

    x = torch.randn(rows, cols, dtype=torch.float16)

    def fn(x):
        with spyre_hint(sliding={"A": {"window": window, "stride": stride}}):
            return x.sum(dim=0)

    x_dev = x.to(DEVICE)
    _pnd.declare_tensor_dim("A", rows)
    _pnd.declare_tensor_dim("B", cols)
    _pnd.name_tensor_dims(x_dev, ["A", "B"])

    before = _snapshot()
    try:
        with config.patch({"lx_planning": True, "allow_all_ops_in_lx_planning": True}):
            got = torch.compile(fn)(x_dev).to("cpu", torch.float32)
    except Exception as e:  # noqa: BLE001 — surface compile/codegen failures
        print(f"  COMPILE/RUN FAILED: {type(e).__name__}: {e}")
        if dump:
            _dump_affine_maps(_snapshot() - before)
        return False

    if dump:
        _dump_affine_maps(_snapshot() - before)

    ref = _cpu_overlap_reference(x, rows, cols, window, stride)
    full = x.to(torch.float32).sum(dim=0)  # what a NON-overlapping read gives
    max_err = (got - ref).abs().max().item()
    ok = torch.allclose(got, ref, rtol=2e-2, atol=ref.abs().max().item() * 2e-2)

    # Peak-matches-but-element-wise-mismatch is the signature of a COLUMN-ORDERING
    # (stick-layout) difference: values correct but permuted.  Compare sorted
    # vectors to tell "right values, reordered" from "wrong values".
    sorted_match = torch.allclose(
        got.sort().values,
        ref.sort().values,
        rtol=2e-2,
        atol=ref.abs().max().item() * 2e-2,
    )

    print(
        f"  overlap ref peak: {ref.abs().max().item():.3f}  "
        f"full-sum peak: {full.abs().max().item():.3f}  "
        f"got peak: {got.abs().max().item():.3f}"
    )
    print(
        f"  max|got - overlap_ref| = {max_err:.4f} -> {'MATCH' if ok else 'MISMATCH'}"
        f"   permutation={bool(sorted_match)}"
    )

    # Per-stick error localisation.  cols split into n_sticks sticks of 64; a
    # slide that works for some sticks but not others shows up as one stick with
    # a large error while the rest are small.
    per_col_err = (got - ref).abs()
    tol = ref.abs().max().item() * 2e-2 + 0.2
    n_match = int((per_col_err <= tol).sum())
    print(f"    columns matching (tol {tol:.2f}): {n_match}/{cols}")
    for s in range(n_sticks):
        lo, hi = s * STICK, (s + 1) * STICK
        print(
            f"    stick {s}: max err cols[{lo}:{hi}] = {per_col_err[lo:hi].max().item():.3f}"
        )
    if not ok:
        worst = per_col_err.argsort(descending=True)[:6].tolist()
        print("    worst cols (col: got vs ref):")
        for c in worst:
            print(
                f"      col {c:>3}: got={got[c].item():>8.2f}  ref={ref[c].item():>8.2f}"
            )
    return bool(ok)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--rows", type=int, default=DEFAULT_ROWS)
    ap.add_argument("--cols", type=int, default=DEFAULT_COLS)
    ap.add_argument("--window", type=int, default=DEFAULT_WINDOW)
    ap.add_argument("--stride", type=int, default=DEFAULT_STRIDE)
    ap.add_argument(
        "--sweep",
        action="store_true",
        help="run the shape-hardening sweep instead of a single shape",
    )
    ap.add_argument(
        "--no-dump",
        action="store_true",
        help="skip the bundle.mlir / geometry dump (quieter sweep output)",
    )
    args = ap.parse_args()

    if args.sweep:
        results = []
        for rows, cols, window, stride in SWEEP_SHAPES:
            ok = run_one(rows, cols, window, stride, dump=not args.no_dump)
            results.append((rows, cols, window, stride, ok))
        print("=" * 78)
        print("SWEEP SUMMARY:")
        for rows, cols, window, stride, ok in results:
            print(
                f"  D={rows:>4} COLS={cols:>4} W={window:>4} S={stride:>4}  "
                f"{'PASS' if ok else 'FAIL'}"
            )
        n_pass = sum(1 for *_, ok in results if ok)
        print(f"  {n_pass}/{len(results)} shapes numerically correct")
    else:
        run_one(args.rows, args.cols, args.window, args.stride, dump=not args.no_dump)


if __name__ == "__main__":
    main()
